export class UserInfo {
  cjr: string; // 创建人
  Cjsj: string; // 创建时间
  lasttime: string; // 上次登录时间
  ui_bgdh: string; // 办公电话
  ui_comm: string; // 备注
  ui_csrq: string; // --出生日期
  ui_czdh: string; // --内线电话
  ui_desc: string; // --用户姓名
  ui_edate: string; // 有效结束日期
  ui_id: string; // 编号
  ui_lx: string; // --用户类型
  ui_mail: string; // 邮箱
  ui_pwd: string; // 密码
  ui_role: string; // 角色
  ui_rzrq: string; // 入职日期
  ui_sdate: string; // 有效开始日期
  ui_sex: string; // 性别
  ui_ssbm: string; // 部门
  ui_ssgs: string; // -所属子公司
  ui_status: string; // 用户状态
  ui_yddx: string; // 移动电话
  ui_zw: string; // 职务
  photo: string; // 照片暂无
}
